---
title: "assignment4"
author: "Claire Wang"
date: "9/17/2020"
output:
  html_document:
    theme: yeti
    toc: true
    toc_float: true
---
<br/>
<br/>
##This assignment is to use network data to find walkshed, bikeshed and motorized-shed.
<br/>
<br/>

```{r setup, include=FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

```{r, message=FALSE}

MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

publicschool<- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/1d9509a8b2fd485d9ad471ba2fdb1f90_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D",quiet = TRUE) 

hospital <-st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/8f1e5741a4ee4c0f82925d17aab3c002_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D", quiet = TRUE) 

openspace <-st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/2868d370c55d4d458d4ae2224ef8cddd_7.kml", quiet = TRUE) 

nhoods <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.kml", quiet = TRUE) %>% 
  filter (Name== "Charlestown" | 
          Name == "South Boston Waterfront" | 
          Name== "South Boston" )  


publicschool <- publicschool[nhoods,] %>%
  st_join(nhoods)

hospital<- hospital[nhoods,] %>%
  st_join(nhoods)

openspace<- openspace[nhoods,] %>%
  st_join(nhoods)


```

```{r, message=FALSE}}
boston_street_features <- opq(bbox = 'Boston MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

boston_streets <- boston_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)

ggplot(boston_streets) +
  geom_sf() +
  theme_map()

```

```{r,message=FALSE}
path_otp <- otp_dl_jar("OTP")

path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
otp_setup(otp = path_otp, dir = path_data, memory =1024)
otpcon <- otp_connect()



```

```{r, message=F}
iso_10min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = publicschool, 
                mode = "WALK", cutoffSec = 600) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_10min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = publicschool, 
                mode = "CAR", cutoffSec = 600) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_10min_drive, iso_10min_walk)

otp_stop()
```
```{r,message=F, fig.size=10}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 10 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


